import { describe, expect, it } from 'vitest';
import { hashPassword, verifyPassword } from '../server/src/auth.js';

/**
 * Every event password on every existing instance is a bcrypt hash sitting in
 * a SQLite file. Nothing re-hashes them; a stored hash is checked against what
 * someone types and that is the whole mechanism. So a bcrypt library upgrade
 * that changed how an old hash is read would not throw, would not fail a
 * build, and would not fail any other test here — it would simply start
 * refusing correct passwords, at an event, in front of a room.
 *
 * These hashes were generated by **bcryptjs 2.4.3**, the version that produced
 * the hashes actually in the wild, and pasted in as literals. That is the
 * point: they cannot be regenerated by the code under test, so they keep
 * meaning "a hash from before" no matter which version is installed.
 */

const FROM_BCRYPTJS_2: Array<[string, string, string]> = [
  [
    'a passphrase with spaces',
    'correct horse battery staple',
    '$2a$10$x64GRCOjY4VIpX6zcfxfN.H7gNXfGI1M0A8y8O9BL3pGOBY3x9FMq',
  ],
  [
    'non-ascii, which is what an umlaut in a password means',
    'pässwörd–✓',
    '$2a$10$GRxiNkYlK7AlwY9/u4UTJe3MS.qw4errY9X9bASVHql4vCOmA5ltK',
  ],
  ['a single character', 'a', '$2a$10$TA7VpVdUN5aJX8Tu4W90aOqXH7SG7yHfSIZLEWjXHFntDGxnD/q.q'],
  [
    'the 72-byte bcrypt ceiling',
    'x'.repeat(72),
    '$2a$10$5Auxn/w6BAVBtBjQwZa2S.gZQ/Mi67Vhi8Jx6fIwawZu39sCb5EUG',
  ],
];

describe('a password hashed by an older release still opens the door', () => {
  for (const [name, plain, hash] of FROM_BCRYPTJS_2) {
    it(name, () => {
      expect(verifyPassword(plain, hash)).toBe(true);
    });
  }

  it('and still refuses the wrong password against those same hashes', () => {
    for (const [name, plain, hash] of FROM_BCRYPTJS_2) {
      // Changed in place, not appended: bcrypt reads 72 bytes and no more, so
      // a difference past that byte is not a difference at all (below).
      const wrong = `Z${plain.slice(1)}`;
      expect(verifyPassword(wrong, hash), name).toBe(false);
      expect(verifyPassword('', hash), name).toBe(false);
    }
  });

  it('still truncates at 72 bytes, as bcrypt has always done', () => {
    // Pinned because it is a property of the algorithm that a rewrite could
    // decide to surface differently — throwing on a longer input, say, which
    // would turn a long stored password into a 500 rather than a sign-in.
    const [, plain, hash] = FROM_BCRYPTJS_2[3]!;
    expect(plain.length).toBe(72);
    expect(verifyPassword(`${plain}ignored`, hash)).toBe(true);
  });

  it('reads the $2a prefix those hashes carry, not only what it writes today', () => {
    // A library that quietly stopped accepting one prefix would lock out every
    // event created before the change.
    expect(FROM_BCRYPTJS_2.every(([, , h]) => h.startsWith('$2a$'))).toBe(true);
  });
});

describe('what it writes now is still readable by itself', () => {
  it('round-trips a fresh hash', () => {
    const hash = hashPassword('a new event password');
    expect(verifyPassword('a new event password', hash)).toBe(true);
    expect(verifyPassword('a new event passwore', hash)).toBe(false);
  });

  it('salts, so the same password twice is two different hashes', () => {
    expect(hashPassword('same')).not.toBe(hashPassword('same'));
  });
});
